language: php
php:
  - '7.0'
  - '7.1'

addons :
  sonarqube: "php"
  token:
    secure: 52afd15d9e9c25fa45fc9ea2cd403c89b07c30dc

script:
   - composer install
   - vendor/bin/phpunit
   - sonar-scanner
