language: php
php:
  - '7.1'
dist: trusty

addons:
  sonarqube: true

install:
  - composer install
script:
  - phpunit
  - vendor/bin/phpunit
after_success:
  - vendor/bin/test-reporter
  - vendor/bin/coveralls -v
  - sonar-scanner -D sonar.host.url=127.0.0.1