language: php
php:
  - '7.1'
dist: trusty
install:
  - composer install
script:
  - phpunit
  -vendor/bin/phpunit
after_success:
  - vendor/bin/test-reporter
  - vendor/bin/coveralls -v
  - sonar-scanner